### ISSUE TITLE
Crash when changing `gl_part_telesplash` from 2 to 0 when teleporting

### ISSUE THREAD

**Issue by matthewearl** [j0zzz/JoeQuake#137]
Repro steps:
1. Set `gl_part_telesplash 2` (or `3`).
2. Step through a teleporter and immediately drop the console (before the splash disappears).
3. Set `gl_part_telesplash 0`.

At this point the game crashes because `clmodel` is `NULL`.

```c
Thread 1 "joequake-gl" received signal SIGSEGV, Segmentation fault.
0x00005555555a255c in R_DrawQ3Model (ent=0x555555816e60 <cl_temp_entities>) at /home/matt/joequake-kugelrund/trunk/gl_rmain.c:2712
2712            if (clmodel->modhint == MOD_Q3TELEPORT)
(gdb) bt
#0  0x00005555555a255c in R_DrawQ3Model (ent=0x555555816e60 <cl_temp_entities>)
    at /home/matt/joequake-kugelrund/trunk/gl_rmain.c:2712
#1  0x00005555555b3a94 in QMB_Q3Teleport (org=0x7fffd7b156c8, alpha=0.886274517)
    at /home/matt/joequake-kugelrund/trunk/gl_rpart.c:2017
#2  0x00005555555ae64e in QMB_DrawParticles () at /home/matt/joequake-kugelrund/trunk/gl_rpart.c:912
#3  0x00005555555fd5f8 in R_DrawParticles () at /home/matt/joequake-kugelrund/trunk/r_part.c:1000
#4  0x00005555555a51d7 in R_RenderScene () at /home/matt/joequake-kugelrund/trunk/gl_rmain.c:3582
#5  0x00005555555a5686 in R_RenderView () at /home/matt/joequake-kugelrund/trunk/gl_rmain.c:3723
#6  0x000055555561978f in V_RenderView () at /home/matt/joequake-kugelrund/trunk/view.c:1547
#7  0x00005555555bce70 in SCR_UpdateScreen () at /home/matt/joequake-kugelrund/trunk/gl_screen.c:1092
#8  0x00005555555c352c in _Host_Frame (time=9.9999999925159955e-07)
    at /home/matt/joequake-kugelrund/trunk/host.c:812
#9  0x00005555555c3868 in Host_Frame (time=9.9999999925159955e-07)
    at /home/matt/joequake-kugelrund/trunk/host.c:892
#10 0x0000555555611af9 in main (argc=4, argv=0x7fffffffdcc8)
    at /home/matt/joequake-kugelrund/trunk/sys_linux.c:328
```

Tested with my SDL linux branch, but also on wine with an official build.

**Comment by j0zzz** [comment]
Fixed in commit 1d1bcb8
